[package]
name = "gen2_test"
version = "0.0.2"
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'framework-mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'framework-mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'

[dependencies.MoveStdlib]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'framework-mainnet'
subdir = 'aptos-move/framework/move-stdlib'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'framework-mainnet'
subdir = 'aptos-move/framework/aptos-token'

[addresses]
# source_addr = "dbc5621916a85792ec7155a96f316e1ddda56726d788b47378b9deb9d8055383"
# keys_custom = "57410cf1141dd18aef4acf956d3c35a9634111642c5ed0ab0d017d634869959b"
# keys_addr = "_"
gen2_mint = "_"
